name: zip_push_s3
on: push
jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Make artifact directory
      run: mkdir -p ./artifacts/${{ github.repository }}

    - name: Create Zip File
      run: |
        ls -lsa
        pwd
        ls src
        zip -r ./artifacts/${{ github.repository }}/${{ github.sha }}.zip ./src

    - name: Push Zip to S3
      uses: jakejarvis/s3-sync-action@v0.3.1
      env:
        SOURCE_DIR: './artifacts'
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: 'zipped-lambda-artifacts-441772730001'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}